### ISSUE TITLE
Linter does not work if the FILE PATH of file is git ignored

### ISSUE THREAD

**Issue by stefaniecg** [a2k-hanlon/linter-veriloghdl#4]
The linter does not work properly if the folder where the file is placed is gitignored.
Took me a while to fiture it out.

The solution is to include the folder in the not ignored folders of the git file, but in my opinion, these two things should not be linked: the git ignore with the linter.

**Comment by a2k-hanlon** [comment]
Hi there, thanks for posting an issue! This behaviour of excluding gitignore'd files from linting is actually dictated by the [linter](https://github.com/steelbrain/linter) package for Atom, which provides the base code linting functionality for many specific language linter packages like this one.

The relevant code in the `linter` package is here: https://github.com/steelbrain/linter/blob/e50316c96c7f699a79982f19338b5d0ae8d835a0/lib/linter-registry.ts#L77 

It's my understanding that this is implemented in the `linter` package as a convenience feature, since files often are ignored because they're auto-generated. That means: a) they probably won't be touched directly by a programmer and b) shouldn't have syntax issues to be linted anyway. However, if you feel that this isn't a one-size-fits-all piece of functionality, I suggest you open an issue on the linter package, perhaps to suggest adding a settings option to toggle this ignore behaviour.

Closing the issue here since it is not a problem with linter-veriloghdl specifically.
